# Generated by Django 4.2 on 2026-02-18 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(help_text='Reference to Customer.id (no FK)')),
                ('customer_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_key', models.TextField(help_text='Full R2 object path/key')),
                ('file_size', models.BigIntegerField(default=0)),
                ('financial_year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('gstr_sheet', models.CharField(blank=True, help_text='Target GSTR sheet (e.g., b2b, hsn)', max_length=50, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
    ]
