# Generated by Django 4.2 on 2026-02-18 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR1Output',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=255)),
                ('financial_year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('storage_key', models.TextField(help_text='R2 path to generated GSTR1 Excel')),
                ('file_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(help_text='CA username who triggered generation', max_length=100)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('verified', 'Verified'), ('corrected', 'Corrected')], default='generated', max_length=20)),
            ],
            options={
                'db_table': 'gstr1_outputs',
            },
        ),
        migrations.CreateModel(
            name='VerificationError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(help_text='Reference to VerificationRun.id')),
                ('gstin', models.CharField(max_length=20)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.CharField(max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('error_type', models.CharField(choices=[('invalid_gstin', 'Invalid GSTIN'), ('cancelled', 'Cancelled GSTIN'), ('inactive', 'Inactive GSTIN'), ('pan_invalid', 'PAN Invalid')], max_length=50)),
                ('cancel_date', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_valid', models.BooleanField(default=False)),
                ('action_taken', models.CharField(default='moved_to_b2cs', max_length=50)),
                ('hsn_adjusted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'verification_errors',
            },
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=255)),
                ('gstr1_output_id', models.UUIDField(help_text='Reference to GSTR1Output.id')),
                ('financial_year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('total_checked', models.IntegerField(default=0)),
                ('total_moved', models.IntegerField(default=0)),
                ('total_pan_errors', models.IntegerField(default=0)),
                ('corrected_key', models.TextField(blank=True, help_text='R2 path to corrected GSTR1 file')),
                ('error_report_key', models.TextField(blank=True, help_text='R2 path to error report Excel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_runs',
            },
        ),
    ]
